# Unit tests for the Python GTF attribute parser logic, exercised via R
# by checking that the regenerated parquet has correct level values.
# These tests validate what the *fixed* parser produces; they will fail
# if run against parquet files generated by the old (broken) parser.

test_that("level column is integer type in genes mcols", {
  gr <- genes(gtf)
  expect_true(is.integer(mcols(gr)$level))
})

test_that("level column is integer type in transcripts mcols", {
  tx <- transcripts(gtf, filter = list(chrom = "chr1"))
  expect_true(is.integer(mcols(tx)$level))
})

# The following two tests will SKIP on the old parquet (all-NA level)
# and PASS once parquet is regenerated with the fixed parser.

test_that("genes level values are in {1, 2, 3} after parser fix", {
  gr <- genes(gtf)
  lv <- mcols(gr)$level
  if (all(is.na(lv))) {
    skip("level column is all-NA: regenerate parquet with fixed gtf_to_parquet.py")
  }
  expect_true(all(lv[!is.na(lv)] %in% 1:3))
})

test_that("most genes have a non-NA level after parser fix", {
  gr <- genes(gtf)
  lv <- mcols(gr)$level
  if (all(is.na(lv))) {
    skip("level column is all-NA: regenerate parquet with fixed gtf_to_parquet.py")
  }
  expect_gt(sum(!is.na(lv)), length(lv) * 0.9)
})
